// payload-types.ts
// HAND-AUTHORED STUB — `npx payload generate:types` fails on Node 22 with
// `ERR_REQUIRE_ASYNC_MODULE` from @payloadcms/richtext-lexical (ESM graph
// with top-level await, required synchronously by Payload's tsx loader).
// See .superpowers/sdd/task-6-report.md for details.
//
// This stub mirrors the shape Payload's generator produces so that imports
// like `Config['collections'][number]['slug']` resolve. Once Node 20 is used
// or Payload fixes the ESM issue, `npx payload generate:types` will overwrite
// this file with the full schema (CollectionConfig-derived types, field
// selects, etc.) and everything downstream keeps working.
//
// Last regenerated by hand: Task 6 (2026-08-10).

/**
 * Collection slugs registered in payload.config.ts.
 *
 * Brand collections (Task 6): users, media, stories, karigars, farms,
 * packaging, occasions. Product stubs (Task 7 expands): mithai-products,
 * gift-boxes, qsr-menu-items, snack-products, merch-products.
 */
export type Collection =
  | "users"
  | "media"
  | "stories"
  | "karigars"
  | "farms"
  | "packaging"
  | "occasions"
  | "mithai-products"
  | "gift-boxes"
  | "qsr-menu-items"
  | "snack-products"
  | "merch-products";

/** Global slugs — none registered yet. */
export type Global = never;

/**
 * Minimal Config mirror. The real generated file carries the full sanitized
 * config object plus per-collection types; this stub carries only what
 * downstream code currently relies on: the slug unions. Add fields here as
 * needed until `payload generate:types` runs cleanly.
 */
export interface Config {
  collections: {
    slug: Collection;
    [key: string]: unknown;
  }[];
  globals: [];
  locale: null | string;
  user: null | {
    id: string | number;
    collection: "users";
    [key: string]: unknown;
  };
}

/** Default export kept for parity with the generated file shape. */
export default Config;
