import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

// iOS Swift codegen. No iOS app consumer exists yet (Task 0.3 v1 ships TS+JSON
// as the contract surface; Kotlin/Swift are committed as reference outputs).
// This stub generates a Swift extension that exposes brand tokens to SwiftUI.

const tokens = JSON.parse(readFileSync(join(process.cwd(), 'tokens.json'), 'utf8'));

function hexToSwiftUIColor(hex: string): string {
  const clean = hex.replace('#', '');
  const r = parseInt(clean.substring(0, 2), 16) / 255;
  const g = parseInt(clean.substring(2, 4), 16) / 255;
  const b = parseInt(clean.substring(4, 6), 16) / 255;
  return `Color(red: ${r.toFixed(4)}, green: ${g.toFixed(4)}, blue: ${b.toFixed(4)})`;
}

const swift = `// AUTO-GENERATED by packages/brand-tokens/scripts/codegen-swift.ts
// Do not edit by hand. Source: packages/brand-tokens/tokens.json
import SwiftUI

extension Color {
  static let mishranBrandCanvas = ${hexToSwiftUIColor(tokens.color.brand.canvas)}
  static let mishranBrandSurface = ${hexToSwiftUIColor(tokens.color.brand.surface)}
  static let mishranBrandAccent = ${hexToSwiftUIColor(tokens.color.brand.accent)}
  static let mishranBrandPop = ${hexToSwiftUIColor(tokens.color.brand.pop)}
  static let mishranBrandInk = ${hexToSwiftUIColor(tokens.color.brand.ink)}

  static let mishranNeutral50 = ${hexToSwiftUIColor(tokens.color.neutral['50'])}
  static let mishranNeutral100 = ${hexToSwiftUIColor(tokens.color.neutral['100'])}
  static let mishranNeutral200 = ${hexToSwiftUIColor(tokens.color.neutral['200'])}
  static let mishranNeutral400 = ${hexToSwiftUIColor(tokens.color.neutral['400'])}
  static let mishranNeutral500 = ${hexToSwiftUIColor(tokens.color.neutral['500'])}
  static let mishranNeutral700 = ${hexToSwiftUIColor(tokens.color.neutral['700'])}
  static let mishranNeutral900 = ${hexToSwiftUIColor(tokens.color.neutral['900'])}

  static let mishranStateSuccess = ${hexToSwiftUIColor(tokens.color.state.success)}
  static let mishranStateWarning = ${hexToSwiftUIColor(tokens.color.state.warning)}
  static let mishranStateError = ${hexToSwiftUIColor(tokens.color.state.error)}
}

extension CGFloat {
  static let mishranRadiusSm: CGFloat = ${parseInt(tokens.radius.sm, 10)}
  static let mishranRadiusMd: CGFloat = ${parseInt(tokens.radius.md, 10)}
  static let mishranRadiusLg: CGFloat = ${parseInt(tokens.radius.lg, 10)}
  static let mishranRadiusXl: CGFloat = ${parseInt(tokens.radius.xl, 10)}

  static let mishranSpacingXs: CGFloat = ${parseInt(tokens.spacing.xs, 10)}
  static let mishranSpacingSm: CGFloat = ${parseInt(tokens.spacing.sm, 10)}
  static let mishranSpacingMd: CGFloat = ${parseInt(tokens.spacing.md, 10)}
  static let mishranSpacingLg: CGFloat = ${parseInt(tokens.spacing.lg, 10)}
  static let mishranSpacingXl: CGFloat = ${parseInt(tokens.spacing.xl, 10)}
  static let mishranSpacingXxl: CGFloat = ${parseInt(tokens.spacing.xxl, 10)}
}

extension Font {
  static let mishranBodySm = Font.system(size: ${tokens.typography.body.sizes.sm})
  static let mishranBodyMd = Font.system(size: ${tokens.typography.body.sizes.md})
  static let mishranBodyLg = Font.system(size: ${tokens.typography.body.sizes.lg})
  static let mishranBodyXl = Font.system(size: ${tokens.typography.body.sizes.xl})
  static let mishranBodyXxl = Font.system(size: ${tokens.typography.body.sizes.xxl})
  static let mishranDisplay = Font.system(size: ${tokens.typography.body.sizes.display})
}
`;

const outDir = join(process.cwd(), 'generated', 'swift');
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'MishranTokens.swift'), swift, 'utf8');
console.log('✓ Wrote generated/swift/MishranTokens.swift');
