import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const tokens = JSON.parse(readFileSync(join(process.cwd(), 'tokens.json'), 'utf8'));

// Helper: convert #RRGGBB hex to Compose Color(0xAARRGGBB). Tokens are opaque.
function hexToComposeColor(hex: string): string {
  const clean = hex.replace('#', '');
  const r = clean.substring(0, 2).toUpperCase();
  const g = clean.substring(2, 4).toUpperCase();
  const b = clean.substring(4, 6).toUpperCase();
  return `0xFF${r}${g}${b}`;
}

const kotlin = `// AUTO-GENERATED by packages/brand-tokens/scripts/codegen-kotlin.ts
// Do not edit by hand. Source: packages/brand-tokens/tokens.json
package com.mishran.app.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.foundation.shape.RoundedCornerShape

object MishranColors {
  val BrandCanvas = Color(${hexToComposeColor(tokens.color.brand.canvas)})
  val BrandSurface = Color(${hexToComposeColor(tokens.color.brand.surface)})
  val BrandAccent = Color(${hexToComposeColor(tokens.color.brand.accent)})
  val BrandPop = Color(${hexToComposeColor(tokens.color.brand.pop)})
  val BrandInk = Color(${hexToComposeColor(tokens.color.brand.ink)})

  val Neutral50 = Color(${hexToComposeColor(tokens.color.neutral['50'])})
  val Neutral100 = Color(${hexToComposeColor(tokens.color.neutral['100'])})
  val Neutral200 = Color(${hexToComposeColor(tokens.color.neutral['200'])})
  val Neutral400 = Color(${hexToComposeColor(tokens.color.neutral['400'])})
  val Neutral500 = Color(${hexToComposeColor(tokens.color.neutral['500'])})
  val Neutral700 = Color(${hexToComposeColor(tokens.color.neutral['700'])})
  val Neutral900 = Color(${hexToComposeColor(tokens.color.neutral['900'])})

  val StateSuccess = Color(${hexToComposeColor(tokens.color.state.success)})
  val StateWarning = Color(${hexToComposeColor(tokens.color.state.warning)})
  val StateError = Color(${hexToComposeColor(tokens.color.state.error)})
}

object MishranRadii {
  val sm = ${parseInt(tokens.radius.sm, 10)}.dp
  val md = ${parseInt(tokens.radius.md, 10)}.dp
  val lg = ${parseInt(tokens.radius.lg, 10)}.dp
  val xl = ${parseInt(tokens.radius.xl, 10)}.dp

  fun shapeSm(): RoundedCornerShape = RoundedCornerShape(sm)
  fun shapeMd(): RoundedCornerShape = RoundedCornerShape(md)
  fun shapeLg(): RoundedCornerShape = RoundedCornerShape(lg)
  fun shapeXl(): RoundedCornerShape = RoundedCornerShape(xl)
}

object MishranSpacing {
  val xs = ${parseInt(tokens.spacing.xs, 10)}.dp
  val sm = ${parseInt(tokens.spacing.sm, 10)}.dp
  val md = ${parseInt(tokens.spacing.md, 10)}.dp
  val lg = ${parseInt(tokens.spacing.lg, 10)}.dp
  val xl = ${parseInt(tokens.spacing.xl, 10)}.dp
  val xxl = ${parseInt(tokens.spacing.xxl, 10)}.dp
}

object MishranType {
  val bodySm: TextUnit = ${tokens.typography.body.sizes.sm}.sp
  val bodyMd: TextUnit = ${tokens.typography.body.sizes.md}.sp
  val bodyLg: TextUnit = ${tokens.typography.body.sizes.lg}.sp
  val bodyXl: TextUnit = ${tokens.typography.body.sizes.xl}.sp
  val bodyXxl: TextUnit = ${tokens.typography.body.sizes.xxl}.sp
  val display: TextUnit = ${tokens.typography.body.sizes.display}.sp
}
`;

const outDir = join(process.cwd(), 'generated', 'kotlin', 'com', 'mishran', 'app', 'ui', 'theme');
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'MishranTokens.kt'), kotlin, 'utf8');
console.log('✓ Wrote generated/kotlin/com/mishran/app/ui/theme/MishranTokens.kt');
