// codegen-ios.ts — Task 20.3 (Mishran Mobile Apps v1).
// Generates Localizable.strings per locale from the JSON source of truth
// into generated/ios/<locale>.lproj — the tree apps/ios/project.yml wires
// into the Mishran + MishranWidgets bundles (the hand-copied
// apps/ios/Mishran/Resources tree is gone; this is the only output).
// Mirrors codegen-android.ts. The L() helper (apps/ios/Mishran/Support/
// Localization.swift) reads these tables and substitutes {token} args.
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const cwd = process.cwd();
const files = readdirSync(cwd).filter((f) => f.endsWith('.json') && f !== 'package.json');

function escapeStrings(s: string): string {
  // .strings format: escape backslashes, double quotes, and newlines.
  return s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n');
}

for (const f of files) {
  const locale = f.replace('.json', '');
  const values: Record<string, string> = JSON.parse(readFileSync(join(cwd, f), 'utf8'));
  // Stable order: follow the JSON file's key order (source of truth).
  let body = '/* Generated by pnpm --filter @mishran/i18n-strings codegen:ios — DO NOT EDIT. Source: packages/i18n-strings/<locale>.json */\n';
  for (const [key, value] of Object.entries(values)) {
    body += `"${key}" = "${escapeStrings(value)}";\n`;
  }

  const outDir = join(cwd, 'generated', 'ios', `${locale}.lproj`);
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, 'Localizable.strings'), body, 'utf8');
  console.log(`✓ ${locale} → ${outDir}/Localizable.strings`);
}
