// scripts/seed-catalog.ts
// Populates `mithai-products` (the core mithai catalog) from real product
// data scraped from public storefronts (Bikanervala, Haldiram's, Anand) for
// local dev/testing. Source data lives in scripts/seed-data/mithai-catalog.json
// (generated by /tmp/scrape/build_catalog.py — re-scrape + rebuild to refresh).
//
// Idempotent: mithai-products upsert by `slug`; media upsert by `alt`
// (one stable alt per image = slug + index). Re-running after a refresh
// updates fields in place and reuses already-uploaded images, so it never
// duplicates media. Image bytes are fetched at seed time from the original
// CDN URLs (nothing binary is committed).
//
// Same harness as scripts/seed.ts (Local API → the dev MongoDB). Run:
//   pnpm seed:catalog
import { getPayload } from "@/lib/payload-client";
import { readFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CATALOG_PATH = resolve(__dirname, "seed-data/mithai-catalog.json");

type CatalogProduct = {
  name: string;
  slug: string;
  family: "classic" | "original" | "sugar-free" | "regional" | "seasonal";
  description: string;
  displayPrice: string;
  images: string[];
  allergens: string[];
  dietaryTags: string[];
  freshnessStatus: string;
  shelfLife: string;
  storage: string;
  source: string;
  sourceUrl: string;
};

// Payload lexical richText: one paragraph of plain text. Same shape as the
// story seed in scripts/seed.ts.
function lexicalParagraph(text: string) {
  return {
    root: {
      type: "root",
      format: "",
      indent: 0,
      version: 1,
      direction: "ltr",
      children: [
        {
          type: "paragraph",
          format: "",
          indent: 0,
          version: 1,
          direction: "ltr",
          textStyle: {},
          textFormat: 0,
          indentLevel: 0,
          children: [
            {
              type: "text",
              format: 0,
              detail: 0,
              mode: "normal",
              style: "",
              textStyles: {},
              version: 1,
              text,
            },
          ],
        },
      ],
    },
  };
}

// Best-effort ingredient line from the product name — clearly placeholder,
// editable in /admin. Only used because mithai-products has no free
// "description" field; `ingredients` is the closest structured slot and the
// catalog API surfaces it.
const INGREDIENT_KEYWORDS: Array<[RegExp, string]> = [
  [/kaju|cashew/i, "cashew"],
  [/badam|almond/i, "almond"],
  [/pista|pistachio/i, "pistachio"],
  [/anjeer|fig/i, "fig"],
  [/khoya|mawa|milk cake/i, "khoya (reduced milk)"],
  [/besan|gram/i, "gram flour"],
  [/atta|wheat/i, "wheat flour"],
  [/til|sesame/i, "sesame"],
  [/gond|dink/i, "edible gum"],
  [/gur|jaggery/i, "jaggery"],
  [/petha/i, "ash gourd"],
  [/khajoor|date/i, "dates"],
  [/chocolate/i, "cocoa"],
  [/paan/i, "betel leaf"],
];
function inferIngredients(p: CatalogProduct): string {
  const parts = new Set<string>();
  for (const [re, label] of INGREDIENT_KEYWORDS) if (re.test(p.name)) parts.add(label);
  if (p.family === "sugar-free") {
    parts.add("natural sweetener");
  } else {
    parts.add("sugar");
  }
  parts.add("ghee");
  parts.add("cardamom");
  return Array.from(parts).join(", ") + ".";
}

async function fetchImageBuffer(url: string) {
  const res = await fetch(url, {
    headers: { "User-Agent": "Mozilla/5.0 (Mishran seed script)" },
    redirect: "follow",
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  const mimetype = res.headers.get("content-type") ?? "image/jpeg";
  const ext = mimetype.includes("png") ? "png" : mimetype.includes("webp") ? "webp" : "jpg";
  const name = `${url.split("/").pop()?.split("?")[0]?.replace(/\.[^.]+$/, "") ?? "image"}.${ext}`;
  return { data: buf, mimetype, name, size: buf.length };
}

// Idempotent media upsert by `alt` (slug-indexed → stable across re-seeds).
async function ensureMedia(payload: Awaited<ReturnType<typeof getPayload>>, url: string, alt: string) {
  const existing = await payload.find({
    collection: "media",
    where: { alt: { equals: alt } },
    limit: 1,
  });
  if (existing.docs.length > 0) return String(existing.docs[0]!.id);
  try {
    const file = await fetchImageBuffer(url);
    const doc = await payload.create({
      collection: "media",
      data: { alt },
      file,
    });
    console.log(`    [media] ${alt}`);
    return String(doc.id);
  } catch (e) {
    console.warn(`    [media SKIP] ${alt}: ${(e as Error).message}`);
    return null;
  }
}

async function main() {
  const catalog = JSON.parse(await readFile(CATALOG_PATH, "utf8")) as { products: CatalogProduct[] };
  const payload = await getPayload();
  console.log(`Seeding ${catalog.products.length} mithai-products from ${CATALOG_PATH}...`);

  let created = 0,
    updated = 0,
    mediaOk = 0,
    mediaSkip = 0;

  for (const p of catalog.products) {
    const imageIds: string[] = [];
    for (let i = 0; i < p.images.length; i++) {
      const id = await ensureMedia(payload, p.images[i]!, `${p.slug}${p.images.length > 1 ? `-${i + 1}` : ""}`);
      if (id) {
        imageIds.push(id);
        mediaOk++;
      } else {
        mediaSkip++;
      }
    }

    const data = {
      name: p.name,
      slug: p.slug,
      family: p.family,
      ingredients: inferIngredients(p),
      allergens: p.allergens,
      dietaryTags: p.dietaryTags,
      shelfLife: p.shelfLife,
      storage: p.storage,
      freshnessStatus: p.freshnessStatus,
      displayPrice: p.displayPrice,
      images: imageIds.map((id) => ({ image: id })),
      story: lexicalParagraph(p.description || `${p.name} — a Mishran house specialty.`),
      _status: "published" as const,
    };

    const existing = await payload.find({
      collection: "mithai-products",
      where: { slug: { equals: p.slug } },
      limit: 1,
    });
    if (existing.docs.length > 0) {
      await payload.update({ collection: "mithai-products", id: existing.docs[0]!.id, data });
      updated++;
    } else {
      await payload.create({ collection: "mithai-products", data });
      created++;
    }
    console.log(`  [${p.family}] ${p.slug} (${imageIds.length} img)`);
  }

  console.log(
    `\nSeed complete: ${created} created, ${updated} updated. Media: ${mediaOk} ok, ${mediaSkip} skipped.`,
  );
  process.exit(0);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
