// scripts/seed-catalog.ts
// Populates `mithai-products` (the core mithai catalog) from real product
// data scraped from public storefronts (Bikanervala, Haldiram's, Anand) for
// local dev/testing. Source data lives in scripts/seed-data/mithai-catalog.json
// (generated by /tmp/scrape/build_catalog.py — re-scrape + rebuild to refresh).
//
// Idempotent: mithai-products upsert by `slug`; media upsert by `alt`
// (one stable alt per image = slug + index). Re-running after a refresh
// updates fields in place and reuses already-uploaded images, so it never
// duplicates media. Image bytes are fetched at seed time from the original
// CDN URLs (nothing binary is committed).
//
// Same harness as scripts/seed.ts (Local API → the dev MongoDB). Run:
//   pnpm seed:catalog
import { getPayload } from "@/lib/payload-client";
import { readFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CATALOG_PATH = resolve(__dirname, "seed-data/mithai-catalog.json");
const SNACKS_PATH = resolve(__dirname, "seed-data/snacks-catalog.json");
const QSR_PATH = resolve(__dirname, "seed-data/qsr-catalog.json");
const GIFT_PATH = resolve(__dirname, "seed-data/gift-catalog.json");

type CatalogProduct = {
  name: string;
  slug: string;
  family: "classic" | "original" | "sugar-free" | "regional" | "seasonal";
  description: string;
  displayPrice: string;
  weight?: string;
  images: string[];
  allergens: string[];
  dietaryTags: string[];
  freshnessStatus: string;
  shelfLife: string;
  storage: string;
  source: string;
  sourceUrl: string;
};

// Fold the scrape's mixed weight spellings ("1 kg" / "1 Kg" / "1kg" / "1Kg",
// "480 gm") into one canonical form: "<n> g" under 1 kg, "<n> kg" at and
// above, non-weights ("1 pack") passed through untouched.
export function normalizeWeight(raw: string | undefined): string | null {
  if (!raw) return null;
  const m = raw.trim().match(/^(\d+(?:\.\d+)?)\s*(kg|Kg|KG|g|gm|grams?)$/);
  if (!m) return raw.trim();
  const value = Number(m[1]);
  if (m[2].toLowerCase().startsWith("kg")) {
    return `${Number.isInteger(value) ? value : value.toFixed(1)} kg`;
  }
  return `${value} g`;
}

// Payload lexical richText: one paragraph of plain text. Same shape as the
// story seed in scripts/seed.ts.
function lexicalParagraph(text: string) {
  return {
    root: {
      type: "root",
      format: "",
      indent: 0,
      version: 1,
      direction: "ltr",
      children: [
        {
          type: "paragraph",
          format: "",
          indent: 0,
          version: 1,
          direction: "ltr",
          textStyle: {},
          textFormat: 0,
          indentLevel: 0,
          children: [
            {
              type: "text",
              format: 0,
              detail: 0,
              mode: "normal",
              style: "",
              textStyles: {},
              version: 1,
              text,
            },
          ],
        },
      ],
    },
  };
}

// Best-effort ingredient line from the product name — clearly placeholder,
// editable in /admin. Only used because mithai-products has no free
// "description" field; `ingredients` is the closest structured slot and the
// catalog API surfaces it.
const INGREDIENT_KEYWORDS: Array<[RegExp, string]> = [
  [/kaju|cashew/i, "cashew"],
  [/badam|almond/i, "almond"],
  [/pista|pistachio/i, "pistachio"],
  [/anjeer|fig/i, "fig"],
  [/khoya|mawa|milk cake/i, "khoya (reduced milk)"],
  [/besan|gram/i, "gram flour"],
  [/atta|wheat/i, "wheat flour"],
  [/til|sesame/i, "sesame"],
  [/gond|dink/i, "edible gum"],
  [/gur|jaggery/i, "jaggery"],
  [/petha/i, "ash gourd"],
  [/khajoor|date/i, "dates"],
  [/chocolate/i, "cocoa"],
  [/paan/i, "betel leaf"],
];
function inferIngredients(p: CatalogProduct): string {
  const parts = new Set<string>();
  for (const [re, label] of INGREDIENT_KEYWORDS) if (re.test(p.name)) parts.add(label);
  if (p.family === "sugar-free") {
    parts.add("natural sweetener");
  } else {
    parts.add("sugar");
  }
  parts.add("ghee");
  parts.add("cardamom");
  return Array.from(parts).join(", ") + ".";
}

async function fetchImageBuffer(url: string) {
  const res = await fetch(url, {
    headers: { "User-Agent": "Mozilla/5.0 (Mishran seed script)" },
    redirect: "follow",
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  const mimetype = res.headers.get("content-type") ?? "image/jpeg";
  const ext = mimetype.includes("png") ? "png" : mimetype.includes("webp") ? "webp" : "jpg";
  const name = `${url.split("/").pop()?.split("?")[0]?.replace(/\.[^.]+$/, "") ?? "image"}.${ext}`;
  return { data: buf, mimetype, name, size: buf.length };
}

// Idempotent media upsert by `alt` (slug-indexed → stable across re-seeds).
async function ensureMedia(payload: Awaited<ReturnType<typeof getPayload>>, url: string, alt: string) {
  const existing = await payload.find({
    collection: "media",
    where: { alt: { equals: alt } },
    limit: 1,
  });
  if (existing.docs.length > 0) return String(existing.docs[0]!.id);
  try {
    const file = await fetchImageBuffer(url);
    const doc = await payload.create({
      collection: "media",
      data: { alt },
      file,
    });
    console.log(`    [media] ${alt}`);
    return String(doc.id);
  } catch (e) {
    console.warn(`    [media SKIP] ${alt}: ${(e as Error).message}`);
    return null;
  }
}

// ---- section catalogs (snacks / qsr / gifts) ----
// These collections have no `slug` field — idempotency is by `name`
// (useAsTitle). Media alt keys are prefixed per section to stay unique.
type SnackProduct = {
  name: string;
  category: "namkeen" | "cookie" | "dry-fruit";
  weight?: string;
  description: string;
  msrp?: string;
  images: string[];
  source: string;
  sourceUrl: string;
};
type QsrItem = {
  name: string;
  category: "chaat" | "chole-bhature" | "kulcha" | "thaali" | "chinese" | "south-indian";
  description: string;
  veg: boolean;
  spiceLevel?: "mild" | "medium" | "hot";
  images: string[];
  source: string;
  sourceUrl: string;
};
type GiftBox = {
  name: string;
  size: "4-piece" | "8-piece" | "16-piece" | "custom";
  compartmentLayout: string;
  images: string[];
  source: string;
  sourceUrl: string;
};

type Stats = { created: number; updated: number; mediaOk: number; mediaSkip: number };

// Resolve image URLs to media ids, updating a stats counter.
async function resolveImages(
  payload: Awaited<ReturnType<typeof getPayload>>,
  urls: string[],
  altPrefix: string,
  stats: Stats,
): Promise<string[]> {
  const ids: string[] = [];
  for (let i = 0; i < urls.length; i++) {
    const id = await ensureMedia(payload, urls[i]!, `${altPrefix}${urls.length > 1 ? `-${i + 1}` : ""}`);
    if (id) {
      ids.push(id);
      stats.mediaOk++;
    } else {
      stats.mediaSkip++;
    }
  }
  return ids;
}

// Upsert a doc into `collection` keyed by name; logs each row.
async function upsertByName(
  payload: Awaited<ReturnType<typeof getPayload>>,
  collection: string,
  name: string,
  data: Record<string, unknown>,
  stats: Stats,
) {
  const existing = await payload.find({ collection, where: { name: { equals: name } }, limit: 1 });
  if (existing.docs.length > 0) {
    await payload.update({ collection, id: existing.docs[0]!.id, data });
    stats.updated++;
  } else {
    await payload.create({ collection, data });
    stats.created++;
  }
}

async function seedSnacks(payload: Awaited<ReturnType<typeof getPayload>>, stats: Stats) {
  const { products } = JSON.parse(await readFile(SNACKS_PATH, "utf8")) as { products: SnackProduct[] };
  console.log(`\nSeeding ${products.length} snack-products...`);
  for (const p of products) {
    const imageIds = await resolveImages(payload, p.images, `snack-${p.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`, stats);
    await upsertByName(
      payload,
      "snack-products",
      p.name,
      {
        name: p.name,
        category: p.category,
        weight: p.weight ?? null,
        description: p.description || null,
        msrp: p.msrp ?? null,
        images: imageIds.map((id) => ({ image: id })),
        externalRetailers: p.sourceUrl ? [{ label: p.source, url: p.sourceUrl }] : [],
      },
      stats,
    );
    console.log(`  [${p.category}] ${p.name}`);
  }
}

async function seedQsr(payload: Awaited<ReturnType<typeof getPayload>>, stats: Stats) {
  const { products } = JSON.parse(await readFile(QSR_PATH, "utf8")) as { products: QsrItem[] };
  console.log(`\nSeeding ${products.length} qsr-menu-items...`);
  for (const p of products) {
    const imageIds = await resolveImages(payload, p.images.slice(0, 1), `qsr-${p.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`, stats);
    await upsertByName(
      payload,
      "qsr-menu-items",
      p.name,
      {
        name: p.name,
        category: p.category,
        description: p.description || null,
        image: imageIds[0] ?? null,
        veg: p.veg,
        spiceLevel: p.spiceLevel ?? "mild",
      },
      stats,
    );
    console.log(`  [${p.category}] ${p.name}`);
  }
}

async function seedGifts(payload: Awaited<ReturnType<typeof getPayload>>, stats: Stats) {
  const { products } = JSON.parse(await readFile(GIFT_PATH, "utf8")) as { products: GiftBox[] };
  console.log(`\nSeeding ${products.length} gift-boxes...`);
  for (const p of products) {
    const imageIds = await resolveImages(payload, p.images, `gift-${p.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`, stats);
    await upsertByName(
      payload,
      "gift-boxes",
      p.name,
      {
        name: p.name,
        size: p.size,
        compartmentLayout: p.compartmentLayout || null,
        images: imageIds.map((id) => ({ image: id })),
      },
      stats,
    );
    console.log(`  [${p.size}] ${p.name}`);
  }
}

async function main() {
  const catalog = JSON.parse(await readFile(CATALOG_PATH, "utf8")) as { products: CatalogProduct[] };
  const payload = await getPayload();
  console.log(`Seeding ${catalog.products.length} mithai-products from ${CATALOG_PATH}...`);

  const stats: Stats = { created: 0, updated: 0, mediaOk: 0, mediaSkip: 0 };

  for (const p of catalog.products) {
    const imageIds = await resolveImages(payload, p.images, p.slug, stats);

    const data = {
      name: p.name,
      slug: p.slug,
      family: p.family,
      ingredients: inferIngredients(p),
      allergens: p.allergens,
      dietaryTags: p.dietaryTags,
      shelfLife: p.shelfLife,
      storage: p.storage,
      freshnessStatus: p.freshnessStatus,
      displayPrice: p.displayPrice,
      weight: normalizeWeight(p.weight),
      images: imageIds.map((id) => ({ image: id })),
      story: lexicalParagraph(p.description || `${p.name} — a Mishran house specialty.`),
      _status: "published" as const,
    };

    const existing = await payload.find({
      collection: "mithai-products",
      where: { slug: { equals: p.slug } },
      limit: 1,
    });
    if (existing.docs.length > 0) {
      await payload.update({ collection: "mithai-products", id: existing.docs[0]!.id, data });
      stats.updated++;
    } else {
      await payload.create({ collection: "mithai-products", data });
      stats.created++;
    }
    console.log(`  [${p.family}] ${p.slug} (${imageIds.length} img)`);
  }

  await seedSnacks(payload, stats);
  await seedQsr(payload, stats);
  await seedGifts(payload, stats);

  console.log(
    `\nSeed complete: ${stats.created} created, ${stats.updated} updated. Media: ${stats.mediaOk} ok, ${stats.mediaSkip} skipped.`,
  );
  process.exit(0);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
