import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { loadCountries } from './countries';

// Kotlin codegen for the sign-in country picker (Android, Compose). The
// generated file is compiled straight into the app via the srcDir wired in
// apps/android/app/build.gradle.kts (same pattern as brand-tokens).

const countries = loadCountries();

function esc(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

const rows = countries
  .map((c) => `        CountryCode(iso2 = "${c.iso2}", name = "${esc(c.name)}", dialCode = "${c.dialCode}"),`)
  .join('\n');

// For dial codes shared by several countries (NANP "1", "44" Crown
// dependencies, ...), the one a customer pasting a full number almost always
// means. Display-only: any tie composes the identical E.164.
const PRIMARY_DIAL_OWNER: Record<string, string> = {
  '1': 'US',
  '7': 'RU',
  '358': 'FI',
  '44': 'GB',
  '47': 'NO',
  '61': 'AU',
  '262': 'RE',
  '590': 'GP',
  '672': 'NF',
};
const byIso2 = new Map(countries.map((c) => [c.iso2, c]));
for (const [dial, iso2] of Object.entries(PRIMARY_DIAL_OWNER)) {
  const row = byIso2.get(iso2);
  if (!row || row.dialCode !== dial) {
    throw new Error(`primaryDialOwner: ${iso2} must exist with dial code ${dial}`);
  }
}
const ownerEntries = Object.entries(PRIMARY_DIAL_OWNER)
  .map(([dial, iso2]) => `        "${dial}" to "${iso2}",`)
  .join('\n');

const kotlin = `// AUTO-GENERATED by packages/country-codes/scripts/codegen-kotlin.ts
// Do not edit by hand. Source: packages/country-codes/countries.json
package com.mishran.app.ui.auth

/**
 * ISO 3166-1 country + ITU E.164 dial code pair for the sign-in country
 * picker. Flag emoji is derived from [iso2] (regional indicators), never
 * stored in countries.json.
 */
data class CountryCode(
    val iso2: String,
    val name: String,
    val dialCode: String,
) {
    /** "+91" — dial code with the E.164 prefix, as displayed and composed. */
    val dialPrefixed: String get() = "+$dialCode"

    /** Regional-indicator flag emoji ("IN" -> India's tricolour). */
    val flagEmoji: String
        get() = iso2.map { ch ->
            Character.toChars(0x1F1E6 + (ch.code - 0x41)).concatToString()
        }.joinToString("")
}

object Countries {
    /** India first (the +91 default), then A–Z by name. This order is the picker order. */
    val all: List<CountryCode> = listOf(
${rows}
    )

    /** The pre-selected country on the sign-in screen. */
    val defaultCountry: CountryCode = all.first()

    fun byIso2(iso2: String): CountryCode? = all.firstOrNull { it.iso2 == iso2 }

    /**
     * Longest-prefix decomposition for a full E.164 number pasted into the
     * national-number field: "919876543210" -> (India, "9876543210"). Ties
     * among equal-length dial codes (NANP "1", "44", ...) prefer the
     * [primaryDialOwner] — the recomposed E.164 is identical either way.
     * Null when [digits] matches no dial code.
     */
    fun longestDialPrefix(digits: String): Pair<CountryCode, String>? {
        var best: CountryCode? = null
        for (c in all) {
            if (!digits.startsWith(c.dialCode)) continue
            val b = best
            when {
                b == null -> best = c
                c.dialCode.length > b.dialCode.length -> best = c
                c.dialCode.length == b.dialCode.length &&
                    primaryDialOwner[c.dialCode] == c.iso2 &&
                    primaryDialOwner[b.dialCode] != b.iso2 -> best = c
            }
        }
        return best?.let { it to digits.substring(it.dialCode.length) }
    }

    /** Tie-break preference for shared dial codes (see longestDialPrefix). */
    private val primaryDialOwner = mapOf(
${ownerEntries}
    )
}
`;

const outDir = join(process.cwd(), 'generated', 'kotlin', 'com', 'mishran', 'app', 'ui', 'auth');
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'Countries.kt'), kotlin, 'utf8');
console.log(`✓ Wrote generated/kotlin/com/mishran/app/ui/auth/Countries.kt (${countries.length} countries)`);
