import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { loadCountries } from './countries';

// Swift codegen for the sign-in country picker (iOS, SwiftUI). The generated
// file is compiled into the Mishran target via project.yml sources (same
// pattern as brand-tokens).

const countries = loadCountries();

function esc(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

const rows = countries
  .map((c) => `        .init(iso2: "${c.iso2}", name: "${esc(c.name)}", dialCode: "${c.dialCode}"),`)
  .join('\n');

// For dial codes shared by several countries (NANP "1", "44" Crown
// dependencies, ...), the one a customer pasting a full number almost always
// means. Display-only: any tie composes the identical E.164.
const PRIMARY_DIAL_OWNER: Record<string, string> = {
  '1': 'US',
  '7': 'RU',
  '358': 'FI',
  '44': 'GB',
  '47': 'NO',
  '61': 'AU',
  '262': 'RE',
  '590': 'GP',
  '672': 'NF',
};
const byIso2 = new Map(countries.map((c) => [c.iso2, c]));
for (const [dial, iso2] of Object.entries(PRIMARY_DIAL_OWNER)) {
  const row = byIso2.get(iso2);
  if (!row || row.dialCode !== dial) {
    throw new Error(`primaryDialOwner: ${iso2} must exist with dial code ${dial}`);
  }
}
const ownerEntries = Object.entries(PRIMARY_DIAL_OWNER)
  .map(([dial, iso2]) => `        "${dial}": "${iso2}",`)
  .join('\n');

const swift = `// AUTO-GENERATED by packages/country-codes/scripts/codegen-swift.ts
// Do not edit by hand. Source: packages/country-codes/countries.json
import Foundation

/// ISO 3166-1 country + ITU E.164 dial code pair for the sign-in country
/// picker. Flag emoji is derived from \`iso2\` (regional indicators), never
/// stored in countries.json.
struct CountryCode: Identifiable, Hashable {
    let iso2: String
    let name: String
    let dialCode: String

    var id: String { iso2 }

    /// "+91" - dial code with the E.164 prefix, as displayed and composed.
    var dialPrefixed: String { "+\\(dialCode)" }

    /// Regional-indicator flag emoji ("IN" -> India's tricolour).
    var flagEmoji: String {
        String(String.UnicodeScalarView(iso2.unicodeScalars.map {
            // A-Z only (validated at codegen), so the scalar is always in range.
            UnicodeScalar(0x1F1E6 + ($0.value - 65))!
        }))
    }

    init(iso2: String, name: String, dialCode: String) {
        self.iso2 = iso2
        self.name = name
        self.dialCode = dialCode
    }
}

enum CountryCodes {
    /// India first (the +91 default), then A-Z by name. This order is the picker order.
    static let all: [CountryCode] = [
${rows}
    ]

    /// The pre-selected country on the sign-in screen.
    static let fallback = all[0]

    static func byIso2(_ iso2: String) -> CountryCode? {
        all.first { $0.iso2 == iso2 }
    }

    /// Longest-prefix decomposition for a full E.164 number pasted into the
    /// national-number field: "919876543210" -> (India, "9876543210"). Ties
    /// among equal-length dial codes (NANP "1", "44", ...) prefer the
    /// primaryDialOwner - the recomposed E.164 is identical either way.
    /// Nil when \`digits\` matches no dial code.
    static func longestDialPrefix(_ digits: String) -> (country: CountryCode, rest: String)? {
        var best: CountryCode?
        for c in all where digits.hasPrefix(c.dialCode) {
            guard let b = best else {
                best = c
                continue
            }
            if c.dialCode.count > b.dialCode.count {
                best = c
            } else if c.dialCode.count == b.dialCode.count,
                      primaryDialOwner[c.dialCode] == c.iso2,
                      primaryDialOwner[b.dialCode] != b.iso2 {
                best = c
            }
        }
        guard let best else { return nil }
        return (best, String(digits.dropFirst(best.dialCode.count)))
    }

    /// Tie-break preference for shared dial codes (see longestDialPrefix).
    private static let primaryDialOwner: [String: String] = [
${ownerEntries}
    ]
}
`;

const outDir = join(process.cwd(), 'generated', 'swift');
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'MishranCountries.swift'), swift, 'utf8');
console.log(`✓ Wrote generated/swift/MishranCountries.swift (${countries.length} countries)`);
